name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Make
      run: sudo apt-get install make

    - name: Run Makefile targets
      run: |
        make -f Makefile1 clean
        make -f Makefile1 check

    - name: Upload pytest.log
      uses: actions/upload-artifact@v3
      with:
        name: pytest-log
        path: ./log/pytest1.log
